{
 "title": "Air quality - SEN55 Sensors",
 "description": "<PUT_DASHBOARD_DESCRIPTION_HERE>",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "SENSOR_NAME",
    "label": "Sensor ID:",
    "query": "SEN55-050,SEN55-051,SEN55-052,SEN55-053, SEN55-054,SEN55-055,SEN55-056,SEN55-057,SEN55-058,SEN55-059,SEN55-060,SEN55-061,SEN55-062,SEN55-063,SEN55-064,SEN55-065,SEN55-066,SEN55-067,SEN55-068,SEN55-069,SEN55-070,SEN55-071,SEN55-072,SEN55-073,SEN55-074,SEN55-075,SEN55-076,SEN55-077,SEN55-078,SEN55-079,SEN55-080,SEN55-081,SEN55-082,SEN55-083,SEN55-084,SEN55-085,SEN55-086,SEN55-087,SEN55-088,SEN55-089,SEN55-090,SEN55-091,SEN55-092,SEN55-093,SEN55-094,SEN55-095,SEN55-096,SEN55-097,SEN55-098,SEN55-099,SEN55-100,SEN55-101,SEN55-102,SEN55-103,SEN55-104,SEN55-105,SEN55-106,SEN55-107,SEN55-108,SEN55-109,SEN55-110,SEN55-111,SEN55-112,SEN55-113,SEN55-114,SEN55-115,SEN55-116,SEN55-117,SEN55-118,SEN55-TEST"
   }
  ]
 },
 "panels": [
  {
   "title": "Particules 2.5µ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"Pm2p5\") AS \"PM2.5\" FROM \"mqtt_consumer\" WHERE (\"topic\"::tag = '<SENSOR_MQTT_TOPIC>/$SENSOR_NAME') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Pm2p5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM2.5" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules 10µ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Pm10p0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM10" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "VOC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "VOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM10" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "NOx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "NOx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM10" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules 2.5µ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Pm2p5",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Pm2p5" ], "type": "field" },
       { "params": [ "Particules 2.5µ" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules 10µ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Pm10p0",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Pm10p0" ], "type": "field" },
       { "params": [ "Particules 10µ" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "VOC",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "VOC" ], "type": "field" },
       { "params": [ "VOC" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "NOx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "NOx",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "NOx" ], "type": "field" },
       { "params": [ "Nox" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Humidité",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       { "params": [ "Humidité" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Température",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       { "params": [ "Température" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules 1µ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Pm1p0",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"Pm1p0\" AS \"Particules 1µ\" FROM \"mqtt_consumer\" WHERE (\"topic\"::tag = '<SENSOR_MQTT_TOPIC>/$SENSOR_NAME') AND $timeFilter",
     "select": [
      [
       { "params": [ "Pm1p0" ], "type": "field" },
       { "params": [ "Particules 1µ" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules 4µ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Pm4p0",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Pm4p0" ], "type": "field" },
       { "params": [ "Particules 4µ" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  },
  {
   "title": "Particules",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Pm1p0",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT time, pm2_5 FROM \"dust_sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "Pm1p0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Particules 1µ" ], "type": "alias" }
      ],
      [
       { "params": [ "Pm2p5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Particules 2.5µ" ], "type": "alias" }
      ],
      [
       { "params": [ "Pm4p0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Particules 4µ" ], "type": "alias" }
      ],
      [
       { "params": [ "Pm10p0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Particules 10µ" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "<SENSOR_MQTT_TOPIC>/$SENSOR_NAME"
      }
     ]
    }
   ]
  }
 ]
}